name: block_crusher
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flame: ^1.5.0
  localstorage: ^4.0.0+1
  percent_indicator: ^4.2.2
  animated_background: ^2.0.0
  audioplayers: ^1.1.1
  shared_preferences: ^2.0.15
  provider: ^6.0.5
  logging: ^1.1.0
  go_router: ^6.0.0
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1

  # If you don't need one of the following dependencies,
  # delete the relevant line below, and get rid of any Dart code
  # that references the dependency.
  firebase_core: ^2.1.1  # Needed for Crashlytics below
  firebase_crashlytics: ^3.0.3  # Error reporting
  games_services: ^3.0.0  # Achievements and leaderboards
  google_mobile_ads: ^2.0.1  # Ads
  in_app_purchase: ^3.0.1  # In-app purchases

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
     - assets/
     - assets/images/
     - assets/music/
     - assets/sfx/


  fonts:
    - family: Permanent Marker
      fonts:
        - asset: assets/Permanent_Marker/PermanentMarker-Regular.ttf
    - family: Quikhand
      fonts:
        - asset: assets/fonts/Quikhand.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon-adaptive-foreground.png"

