name: block_crusher
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flame: ^1.5.0
  localstorage: ^4.0.0+1
  percent_indicator: ^4.2.2
  animated_background: ^2.0.0
  audioplayers: ^1.1.1
  shared_preferences: ^2.0.15
  provider: ^6.0.5
  logging: ^1.1.0
  go_router: ^6.0.0
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1

  # If you don't need one of the following dependencies,
  # delete the relevant line below, and get rid of any Dart code
  # that references the dependency.
  firebase_core: ^2.1.1  # Needed for Crashlytics below
  firebase_crashlytics: ^3.0.3  # Error reporting
  games_services: ^3.0.0  # Achievements and leaderboards
  google_mobile_ads: ^2.0.1  # Ads
  in_app_purchase: ^3.0.1  # In-app purchases
  dotted_border: ^2.0.0+3
  flame_forge2d: ^0.12.4
  firebase_remote_config: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
     - assets/
     - assets/images/
     - assets/images/food/
     - assets/images/food/100x215/
     - assets/images/food/100x250/
     - assets/images/food/150x275/
     - assets/images/food/200x250/
     - assets/images/food/200x285/
     - assets/images/food/300x120/
     - assets/images/food/300x150/
     - assets/images/food/300x215/
     - assets/images/food/300x250/
     - assets/images/food/300x275/
     - assets/images/food/300x300/
     - assets/images/characters_skill_game/
     - assets/images/characters/
     - assets/images/characters/300x280/
     - assets/images/characters/500x210/
     - assets/images/characters/700x525/
     - assets/images/characters/1000x480/
     - assets/images/characters/1000x600/
     - assets/images/characters/1000x900/
     - assets/images/characters/bots/
     - assets/images/characters/bots/1000x666/
     - assets/images/characters/fish/
     - assets/images/characters/fish/1000x666/
     - assets/images/characters/fish/1000x1000/
     - assets/images/characters/hoomy/
     - assets/images/characters/hoomy/1000x666/
     - assets/images/characters/hoomy/1000x1000/
     - assets/images/characters/hoomy_with_weapon/
     - assets/images/characters/hoomy_with_weapon/1000x666/
     - assets/images/characters/object/
     - assets/images/characters/object/1000x666/
     - assets/images/characters/object/1000x1000/
     - assets/images/enemy/
     - assets/images/enemy/trippie/
     - assets/images/enemy/trippie/1000x850/
     - assets/images/points/
     - assets/images/heart/
     - assets/images/characters/aliens/
     - assets/images/characters/aliens/s/
     - assets/images/coins/
     - assets/images/coins/1000x677/
     - assets/images/coins/1000x750/
     - assets/images/coins/1000x900/
     - assets/images/coins/1000x1000/
     - assets/images/backgrounds/
     - assets/images/animation/
     - assets/music/
     - assets/sfx/
     - assets/sfx/lea/
     


  fonts:
    - family: Permanent Marker
      fonts:
        - asset: assets/Permanent_Marker/PermanentMarker-Regular.ttf
    - family: Quikhand
      fonts:
        - asset: assets/fonts/Quikhand.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon-adaptive-foreground.png"

